apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: xg1d2f9vn-nodejs 
  janus-idp.io/tekton: xg1d2f9vn-nodejs
  backstage.io/kubernetes-id: xg1d2f9vn-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xg1d2f9vn-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml