apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: xg1d2f9vn-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xg1d2f9vn-nodejs 
  name: xg1d2f9vn-nodejs
spec:
  port:
    targetPort: 3001 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: xg1d2f9vn-nodejs
    weight: 100 
